### ISSUE TITLE
Bug: V5.6 Cross Site Scripting Vulnerability

### ISSUE THREAD

**Issue by lolipop1234** [gaozhifeng/PHPMyWind#7]
There is an xss vulnerability in your latest version of the v5.6

No security check in page phpmywind/admin/infolist_add.php
![image](https://user-images.githubusercontent.com/30997848/64229427-51356b00-cf1c-11e9-86f5-1467b6d48854.png)

When I add a new article, I use "<script>alert(/xss/)</script>" as the title
![image](https://user-images.githubusercontent.com/30997848/64229604-d3259400-cf1c-11e9-9b84-f267a35869b7.png)
then back to the PHPMYWIND/admin/infolist.php 
![image](https://user-images.githubusercontent.com/30997848/64229711-1e3fa700-cf1d-11e9-9d29-59e062f08eaf.png)
background page executed a javascript script

javascript also executed on mainpage
![image](https://user-images.githubusercontent.com/30997848/64230411-61027e80-cf1f-11e9-834a-71feeb60f7ac.png)

Fix:

Strictly verify user input, you must perform strict checks and html escape escaping on all input scripts, iframes, etc. The input here is not only the input interface that the user can directly interact with, but also the variables in the HTTP request in the HTTP request, the variables in the HTTP request header, and so on.
Verify the data type and verify its format, length, scope, and content.
Not only need to be verified on the client side but also on the server side.
The output data should also be checked. The values in the database may be output in multiple places on a large website. Even if the input is coded, the security check should be performed at the output points.

**Comment by lolipop1234** [comment]
javascript  also executed on mainpage

![Uploading image.png…]()

**Comment by duyueping** [comment]
Thank you
